none:
	@grep "####" Makefile | grep -v grep | sed -e 's/####//'

cart: #### setup cart components
	@bash components/cart.sh

catalogue: #### setup catalogue components
	@bash components/catalogue.sh

user: #### setup user components
	@bash components/user.sh

shipping: #### setup shipping components
	@bash components/shipping.sh

payment: #### setup payment components
	@bash components/payment.sh

frontend: #### setup frontend components
	@bash components/frontend.sh

mysql: #### setup mysql components
	@bash components/mysql.sh

redis: #### setup redis components
	@bash components/redis.sh

rabbitmq: #### setup rabbitmq components
	@bash components/rabbitmq.sh

mongodb: #### setup mongodb components
	@bash components/mongodb.sh





